version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1
    steps:
      - checkout

      - run: sudo apt update
      - run: make

      - store_artifacts:
          path: build/auth-cas.phar
