version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1
    environment:
      CROWDIN_PROJECT: $CROWDIN_PROJECT
      CROWDIN_API_KEY: $CROWDIN_API_KEY
    steps:
      - checkout
      - attach_workspace:
            at: /tmp/workspace

      - run: sudo apt update
      - run: make

      - persist_to_workspace:
          root: .
          paths:
            - build

      - store_artifacts:
          path: build/auth-cas.phar
  publish-github-release:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr \
              -t ${GITHUB_TOKEN} \
              -u ${CIRCLE_PROJECT_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} \
              -c ${CIRCLE_SHA1} \
              -delete \
              ${CIRCLE_TAG} /tmp/workspace/build/auth-cas.phar

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

